services:
  cbers-colorize:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: cpu
    image: cbers-colorize:cpu
    container_name: cbers-colorize-cpu
    volumes:
      - ./data:/data:ro
      - ./out:/out
    working_dir: /app
    environment:
      # inócuo em CPU, mas pode manter sem problema
      PYTORCH_CUDA_ALLOC_CONF: "max_split_size_mb:128,garbage_collection_threshold:0.8"